spring:
  application:
    name: customer-mortgage
  profiles:
    active: dev
  jpa:
    database: H2
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:customer-mortgage
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: trace


springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      agifyCircuitBreaker:
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 3000
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true